version: '2'
services:
        db:
                image: mysql:5.6
                environment:
                        - MYSQL_ROOT_PASSWORD=secret
                        - MYSQL_DATABASE=cakephp
                        - MYSQL_USER=cakephp
                        - MYSQL_PASSWORD=secret
