version: '2'
services:
        db:
                image: mysql:5.6
                environment:
                        - MYSQL_ROOT_PASSWORD=secret
                        - MYSQL_DATABASE=cakephp
                        - MYSQL_USER=cakephp
                        - MYSQL_PASSWORD=secret
                ports:
                        - '3306:3306'
        web:
                build: web                
                environment:
                        DB_HOST: db
                volumes:
                        - ./src:/var/www/html
                ports:
                        - 80:80
                links:
                        - db
